// Slangmaxxer - Looksmaxxing / PSL Text Converter
// The most comprehensive looksmaxxing text converter on the market
const originalTexts = new Map();

// ---------------------------------------------------------------------------
// LOOKSMAXXING SLANG DICTIONARY
// Level 1 — Softmaxxed: core PSL/lookism vocabulary, anatomy, ratings
// Level 2 — Hardmaxxed: -cel/-pilled/-fraud compounds, deep community jargon,
//           techniques, procedures, sentence-level rewrites
// Level 3 — GIGAMOGGED: full unhinged schizo-posting, ALL CAPS outbursts,
//           random PSL analysis injections, chaotic sentence endings
//
// Multi-word phrases MUST come before single-word entries so they match first.
// Replacements are cumulative: level 2 includes level 1, level 3 includes 1+2.
// ---------------------------------------------------------------------------

const slangLevels = {
  // =========================================================================
  //  LEVEL 1 — SOFTMAXXED
  // =========================================================================
  1: [
    // ── Multi-word phrases (must come first) ──────────────────────────────
    [/\bgood looking\b/gi, "high-tier PSL"],
    [/\bgood-looking\b/gi, "high-tier PSL"],
    [/\bbone structure\b/gi, "skeletal framework PSL base"],
    [/\bplastic surgery\b/gi, "hardmaxx"],
    [/\bbody fat\b/gi, "BF%"],
    [/\bbody language\b/gi, "frame language"],
    [/\bfacial hair\b/gi, "facial hair density"],
    [/\bhair loss\b/gi, "Norwooding"],
    [/\bhair transplant\b/gi, "Norwood reversal surgery"],
    [/\beye contact\b/gi, "deeplock"],
    [/\bfirst impression\b/gi, "initial PSL read"],
    [/\bself improvement\b/gi, "looksmaxxing"],
    [/\bself-improvement\b/gi, "looksmaxxing"],
    [/\bworking out\b/gi, "gymmaxxing"],
    [/\bwork out\b/gi, "gymmaxx"],
    [/\bwork hard\b/gi, "grindmaxx"],
    [/\bgiving up\b/gi, "going LDAR"],
    [/\bgave up\b/gi, "went full LDAR"],
    [/\bgive up\b/gi, "LDAR"],
    [/\bin love\b/gi, "oneitis-locked"],
    [/\bfell in love\b/gi, "caught oneitis"],
    [/\bfalling in love\b/gi, "developing oneitis"],
    [/\bran into\b/gi, "got brutally mogged by"],
    [/\blooked at\b/gi, "ran a PSL audit on"],
    [/\bsat down\b/gi, "collapsed frame"],
    [/\bbetter than\b/gi, "mogging"],
    [/\bworse than\b/gi, "mogged by"],
    [/\bcompared to\b/gi, "PSL-benchmarked against"],
    [/\bglow up\b/gi, "ascension arc"],
    [/\bglow-up\b/gi, "ascension arc"],
    [/\bdouble chin\b/gi, "submental fat deposit"],
    [/\bdark circles\b/gi, "infraorbital hollowing"],
    [/\bbad genetics\b/gi, "cursed genetic RNG"],
    [/\bgood genetics\b/gi, "blessed genetic RNG"],
    [/\bside profile\b/gi, "lateral PSL audit"],
    [/\bfront facing\b/gi, "frontal PSL audit"],
    [/\bhigh cheekbones\b/gi, "prominent zygomatic projection"],
    [/\breceding hairline\b/gi, "advancing Norwood"],
    [/\bweight loss\b/gi, "leanmaxxing arc"],
    [/\bweight gain\b/gi, "bloatmaxxing"],
    [/\bmuscle mass\b/gi, "lean mass"],
    [/\bsocial media\b/gi, "SMV broadcasting platform"],
    [/\bsocial skills\b/gi, "NT abilities"],
    [/\bmental health\b/gi, "cortisol management"],
    [/\bself esteem\b/gi, "internal aura calibration"],
    [/\bself-esteem\b/gi, "internal aura calibration"],
    [/\bpeer pressure\b/gi, "social mogging"],
    [/\bfat loss\b/gi, "leanmaxxing"],
    [/\bdating app\b/gi, "SMV sorting algorithm"],
    [/\bdating apps\b/gi, "SMV sorting algorithms"],
    [/\bonline dating\b/gi, "digital SMV marketplace"],

    // ── People / archetypes ───────────────────────────────────────────────
    [/\bpeople\b/gi, "normies"],
    [/\beveryone\b/gi, "every normie"],
    [/\bnobody\b/gi, "not a single specimen"],
    [/\bsomeone\b/gi, "some specimen"],
    [/\banyone\b/gi, "any specimen"],
    [/\bperson\b/gi, "specimen"],
    [/\bpersons\b/gi, "specimens"],
    [/\bmen\b/gi, "mogs"],
    [/\bman\b/gi, "mog"],
    [/\bwomen\b/gi, "stacys"],
    [/\bwoman\b/gi, "stacy"],
    [/\bgirls\b/gi, "stacys"],
    [/\bgirl\b/gi, "stacy"],
    [/\bguys\b/gi, "chadlites"],
    [/\bguy\b/gi, "chadlite"],
    [/\bboys\b/gi, "youngcels"],
    [/\bboy\b/gi, "youngcel"],
    [/\bfriends\b/gi, "the lookism crew"],
    [/\bfriend\b/gi, "gymcel buddy"],
    [/\benemies\b/gi, "moggERs"],
    [/\benemy\b/gi, "moggER"],
    [/\bboss\b/gi, "alpha AMOG"],
    [/\bleader\b/gi, "top-tier mogger"],
    [/\bcelebrities\b/gi, "PSL gods"],
    [/\bcelebrity\b/gi, "PSL god"],
    [/\bteam\b/gi, "lookism crew"],
    [/\bgroup\b/gi, "mog squad"],
    [/\bcrowd\b/gi, "mog gauntlet"],
    [/\bstranger\b/gi, "random NPC"],
    [/\bstrangers\b/gi, "random NPCs"],
    [/\bneighbor\b/gi, "proximity specimen"],
    [/\bneighbors\b/gi, "proximity specimens"],
    [/\bbrother\b/gi, "genetic co-recipient"],
    [/\bsibling\b/gi, "genetic co-recipient"],
    [/\bbaby\b/gi, "fresh spawn"],
    [/\bchild\b/gi, "pre-puberty specimen"],
    [/\bchildren\b/gi, "pre-puberty specimens"],
    [/\bkids\b/gi, "pre-puberty specimens"],
    [/\bteenager\b/gi, "puberty-stage specimen"],
    [/\bteenagers\b/gi, "puberty-stage specimens"],
    [/\badult\b/gi, "fully-developed specimen"],
    [/\badults\b/gi, "fully-developed specimens"],
    [/\belderly\b/gi, "post-wall veteran"],
    [/\bmodel\b/gi, "PSL 8+ specimen"],
    [/\bmodels\b/gi, "PSL 8+ specimens"],
    [/\bactor\b/gi, "statusmaxxed specimen"],
    [/\bactors\b/gi, "statusmaxxed specimens"],
    [/\bathlete\b/gi, "framemaxxed specimen"],
    [/\bathletes\b/gi, "framemaxxed specimens"],
    [/\bhero\b/gi, "gigachad"],
    [/\bheroes\b/gi, "gigachads"],
    [/\bvillain\b/gi, "dark triad specimen"],
    [/\bking\b/gi, "top mogger"],
    [/\bqueen\b/gi, "gigastacy"],

    // ── Face / cranial anatomy ────────────────────────────────────────────
    [/\bfaces\b/gi, "facial structures"],
    [/\bface\b/gi, "facial structure"],
    [/\bjawline\b/gi, "gonial angle"],
    [/\bjaws\b/gi, "mandibles"],
    [/\bjaw\b/gi, "mandible"],
    [/\bcheekbones\b/gi, "zygomatic arches"],
    [/\bcheekbone\b/gi, "zygomatic arch"],
    [/\bcheeks\b/gi, "buccal region"],
    [/\bcheek\b/gi, "buccal fat pad"],
    [/\bchin\b/gi, "mental protuberance"],
    [/\bnose\b/gi, "nasal bridge"],
    [/\bnostrils\b/gi, "nasal apertures"],
    [/\beyes\b/gi, "canthal tilt"],
    [/\beye\b/gi, "orbital structure"],
    [/\beyebrows\b/gi, "brow ridges"],
    [/\beyebrow\b/gi, "brow ridge"],
    [/\beyelids\b/gi, "upper eyelid exposure zones"],
    [/\beyelid\b/gi, "UEE zone"],
    [/\bforehead\b/gi, "frontal bone"],
    [/\bheads\b/gi, "skulls"],
    [/\bhead\b/gi, "skull"],
    [/\bskull\b/gi, "cranial structure"],
    [/\bneck\b/gi, "neck circumference"],
    [/\blips\b/gi, "vermilion border"],
    [/\blip\b/gi, "vermilion"],
    [/\bteeth\b/gi, "maxillary dentition"],
    [/\btooth\b/gi, "dental unit"],
    [/\bsmile\b/gi, "maxilla exposure"],
    [/\bsmiling\b/gi, "maxilla-exposing"],
    [/\bsmiled\b/gi, "exposed maxilla"],
    [/\bfrown\b/gi, "negative canthal expression"],
    [/\bbrow\b/gi, "supraorbital ridge"],
    [/\bhairline\b/gi, "Norwood status"],
    [/\bbald\b/gi, "Norwood 7"],
    [/\bbalding\b/gi, "Norwooding"],
    [/\bhair\b/gi, "follicular status"],
    [/\bbeard\b/gi, "facial hair density"],
    [/\bwrinkles\b/gi, "collagen degradation"],
    [/\bwrinkle\b/gi, "collagen bleed"],
    [/\bskin\b/gi, "dermal layer"],
    [/\bacne\b/gi, "dermal inflammation"],
    [/\bpimple\b/gi, "PSL-reducing eruption"],
    [/\bpimples\b/gi, "PSL-reducing eruptions"],
    [/\bfreckles\b/gi, "melanin distribution markers"],
    [/\bscar\b/gi, "dermal failo"],
    [/\bscars\b/gi, "dermal failos"],
    [/\bears\b/gi, "auricular structures"],
    [/\bear\b/gi, "auricular structure"],
    [/\btongue\b/gi, "mewing apparatus"],
    [/\bpalate\b/gi, "maxillary palate"],
    [/\bdimples\b/gi, "buccal halo indicators"],

    // ── Body / frame ──────────────────────────────────────────────────────
    [/\bbody\b/gi, "frame"],
    [/\bbodies\b/gi, "frames"],
    [/\bshoulders\b/gi, "clavicular width"],
    [/\bshoulder\b/gi, "clavicle"],
    [/\bchest\b/gi, "pectoral insertions"],
    [/\barms\b/gi, "arm proportions"],
    [/\barm\b/gi, "arm proportion"],
    [/\bbiceps\b/gi, "bicep insertions"],
    [/\btriceps\b/gi, "tricep insertions"],
    [/\bwaist\b/gi, "adonis belt region"],
    [/\bhips\b/gi, "hip-to-shoulder ratio zone"],
    [/\blegs\b/gi, "femur-to-tibia proportions"],
    [/\bleg\b/gi, "lower limb proportion"],
    [/\bcalves\b/gi, "calf insertions"],
    [/\bmuscles\b/gi, "lean mass"],
    [/\bmuscle\b/gi, "lean mass"],
    [/\babs\b/gi, "rectus abdominis visibility"],
    [/\bweight\b/gi, "body composition"],
    [/\bfat\b/gi, "subcutaneous adipose tissue"],
    [/\boverweight\b/gi, "bloatmaxxed"],
    [/\bthin\b/gi, "leanmaxxed"],
    [/\bskinny\b/gi, "lanklet-mode"],
    [/\bfit\b/gi, "aesthetically optimized"],
    [/\bmuscular\b/gi, "framemaxxed"],
    [/\bbuff\b/gi, "roidmaxxed"],
    [/\bstrong\b/gi, "compound-lift-pilled"],
    [/\bweak\b/gi, "DYEL-tier"],
    [/\bwrists\b/gi, "wrist circumferences"],
    [/\bwrist\b/gi, "wrist circumference"],
    [/\bhands\b/gi, "grip indicators"],
    [/\bhand\b/gi, "grip indicator"],
    [/\bfingers\b/gi, "digit ratios"],
    [/\bfeet\b/gi, "lower extremities"],
    [/\bback\b/gi, "V-taper region"],
    [/\bspine\b/gi, "postural axis"],
    [/\bposture\b/gi, "spinal alignment"],
    [/\bveins\b/gi, "vascularity markers"],

    // ── Height ────────────────────────────────────────────────────────────
    [/\btall\b/gi, "heightmaxxed"],
    [/\btaller\b/gi, "more heightmogging"],
    [/\btallest\b/gi, "peak heightmog"],
    [/\bshort\b/gi, "heightmogged"],
    [/\bshorter\b/gi, "more heightmogged"],
    [/\bshortest\b/gi, "maximum manlet-tier"],
    [/\bheight\b/gi, "vertical SMV multiplier"],

    // ── Attractiveness / PSL ratings ──────────────────────────────────────
    [/\bhandsome\b/gi, "high PSL"],
    [/\bbeautiful\b/gi, "PSL 7+"],
    [/\bgorgeous\b/gi, "PSL 8+"],
    [/\bstunning\b/gi, "mogger-tier PSL"],
    [/\battractive\b/gi, "high SMV"],
    [/\bpretty\b/gi, "facially harmonious"],
    [/\bcute\b/gi, "neotenous"],
    [/\bugly\b/gi, "subhuman-tier PSL"],
    [/\bunattractive\b/gi, "sub-5 PSL"],
    [/\bunpleasant\b/gi, "negatively-canthal-tilted"],
    [/\baverage\b/gi, "normie-tier"],
    [/\bnormal\b/gi, "normie-tier"],
    [/\bmediocre\b/gi, "MTN at best"],
    [/\blooks\b/gi, "PSL rating"],
    [/\blook\b/gi, "aesthetic"],
    [/\bappearance\b/gi, "phenotype"],
    [/\bstyle\b/gi, "looksmaxxed aesthetic"],
    [/\bfashion\b/gi, "stylemaxxing"],
    [/\bclothes\b/gi, "softmaxx gear"],
    [/\bclothing\b/gi, "softmaxx gear"],
    [/\boutfit\b/gi, "softmaxx loadout"],
    [/\boutfits\b/gi, "softmaxx loadouts"],
    [/\bglasses\b/gi, "orbital-framing devices"],
    [/\bsunglasses\b/gi, "UV dodgemaxxing shields"],
    [/\bjewelry\b/gi, "statusmaxx accessories"],
    [/\bwatch\b/gi, "wrist statusmaxx piece"],
    [/\bperfume\b/gi, "pheromone fraud"],
    [/\bcologne\b/gi, "pheromone fraud spray"],
    [/\bdeodorant\b/gi, "hygienemaxx essential"],
    [/\bshampoo\b/gi, "follicular maintenance fluid"],
    [/\bsoap\b/gi, "dermal cleansing agent"],

    // ── Looksmaxxing verbs ────────────────────────────────────────────────
    [/\bimprove\b/gi, "maxx"],
    [/\bimproving\b/gi, "maxxing"],
    [/\bimproved\b/gi, "maxxed"],
    [/\bimprovement\b/gi, "maxxing gains"],
    [/\bimprovements\b/gi, "ascension vectors"],
    [/\boptimize\b/gi, "looksmaxx"],
    [/\boptimizing\b/gi, "looksmaxxing"],
    [/\benhance\b/gi, "ascend"],
    [/\benhancing\b/gi, "ascending"],
    [/\benhanced\b/gi, "ascended"],
    [/\bchange\b/gi, "softmaxx"],
    [/\bchanged\b/gi, "softmaxxed"],
    [/\bchanging\b/gi, "softmaxxing"],
    [/\btransform\b/gi, "hardmaxx"],
    [/\btransformation\b/gi, "hardmaxx ascension"],
    [/\bsurgery\b/gi, "hardmaxxing procedure"],
    [/\bprocedure\b/gi, "surgical intervention"],
    [/\bexercise\b/gi, "gymmaxx"],
    [/\bexercising\b/gi, "gymmaxxing"],
    [/\bworkout\b/gi, "gymmaxx session"],
    [/\bworkouts\b/gi, "gymmaxx sessions"],
    [/\bgym\b/gi, "the iron temple"],
    [/\bdiet\b/gi, "leanmaxxing protocol"],
    [/\bdieting\b/gi, "leanmaxxing"],
    [/\bskincare\b/gi, "skinmaxxing routine"],
    [/\bgrooming\b/gi, "groommaxxing"],
    [/\btan\b/gi, "melaninmaxx"],
    [/\btanning\b/gi, "melaninmaxxing"],
    [/\btanned\b/gi, "melaninmaxxed"],
    [/\bsunscreen\b/gi, "UV dodgemaxxing cream"],
    [/\bmoisturizer\b/gi, "dermal hydration protocol"],
    [/\bretinol\b/gi, "collagen-boosting compound"],
    [/\bshower\b/gi, "hygienemaxx session"],
    [/\bshave\b/gi, "facial hair fraud-adjustment"],
    [/\bshaving\b/gi, "facial hair fraud-adjusting"],
    [/\bhaircut\b/gi, "follicular reconfig"],
    [/\bmakeup\b/gi, "fakeup (fraudmaxxing)"],

    // ── Mewing / techniques ───────────────────────────────────────────────
    [/\btongue posture\b/gi, "mewing form"],
    [/\bbreathing\b/gi, "nasal breathing protocol"],
    [/\bchewing\b/gi, "gummaxxing"],
    [/\bchewing gum\b/gi, "falim gum"],
    [/\bstretching\b/gi, "flexibilitymaxxing"],
    [/\bjogging\b/gi, "cardiomaxxing"],
    [/\brunning\b/gi, "cardiomaxxing"],
    [/\bswimming\b/gi, "aquamaxxing"],
    [/\byoga\b/gi, "posturemaxxing"],
    [/\bmeditation\b/gi, "cortisol stabilization protocol"],
    [/\bmeditating\b/gi, "cortisolmaxxing"],
    [/\blifting\b/gi, "compound-lift-maxxing"],
    [/\blifting weights\b/gi, "compound-lift-maxxing"],
    [/\bpush ups\b/gi, "calisthenics-maxxing"],
    [/\bpushups\b/gi, "calisthenics-maxxing"],
    [/\bsit ups\b/gi, "core-maxxing"],
    [/\bcardio\b/gi, "cardiomaxxing"],

    // ── Mogging / competition ─────────────────────────────────────────────
    [/\boutshine\b/gi, "brutally mog"],
    [/\boutshined\b/gi, "brutally mogged"],
    [/\bbeat\b/gi, "AMOG"],
    [/\bbeaten\b/gi, "AMOGed"],
    [/\bcompete\b/gi, "mog-battle"],
    [/\bcompeting\b/gi, "mog-battling"],
    [/\bcompetition\b/gi, "mog-off"],
    [/\bdominate\b/gi, "brutalMOG"],
    [/\bdominated\b/gi, "brutally mogged"],
    [/\bdominating\b/gi, "brutalMOGGING"],
    [/\bintimidate\b/gi, "framemog"],
    [/\bintimidating\b/gi, "framemogging"],
    [/\bintimidated\b/gi, "framemogged"],
    [/\bsuperior\b/gi, "mogger-tier"],
    [/\binferior\b/gi, "mogged-tier"],
    [/\bimpressive\b/gi, "mog-worthy"],
    [/\bunimpressive\b/gi, "subhuman-tier"],
    [/\boverpowered\b/gi, "gigamogged"],
    [/\boverpower\b/gi, "gigamog"],
    [/\bsurpass\b/gi, "heightmog"],
    [/\bsurpassed\b/gi, "heightmogged"],
    [/\bhumiliate\b/gi, "skullmog"],
    [/\bhumiliated\b/gi, "skullmogged"],
    [/\bhumiliating\b/gi, "skullmogging"],
    [/\bcrush\b/gi, "framemog into oblivion"],
    [/\bcrushed\b/gi, "framemogged into oblivion"],
    [/\bdefeated\b/gi, "mogged into submission"],
    [/\bdestroyed\b/gi, "BRUTALLY mogged"],
    [/\bwon\b/gi, "out-mogged"],
    [/\blost\b/gi, "got mogged"],

    // ── Cope / fraud / delusion ───────────────────────────────────────────
    [/\bexcuses\b/gi, "copes"],
    [/\bexcuse\b/gi, "cope"],
    [/\bdenial\b/gi, "maximum cope"],
    [/\bdelusional\b/gi, "full-cope-mode"],
    [/\bdelusion\b/gi, "turbo-cope"],
    [/\bpretend\b/gi, "fraud"],
    [/\bpretending\b/gi, "frauding"],
    [/\bpretended\b/gi, "frauded"],
    [/\bfake\b/gi, "frauded"],
    [/\bfaking\b/gi, "fraudmaxxing"],
    [/\blie\b/gi, "cope-narrative"],
    [/\blying\b/gi, "copemaxxing"],
    [/\blied\b/gi, "cope-narrated"],
    [/\bhopeless\b/gi, "it's over"],
    [/\bhope\b/gi, "cope"],
    [/\bhoping\b/gi, "coping"],
    [/\bdoubt\b/gi, "blackpilled uncertainty"],
    [/\bdoubting\b/gi, "approaching the blackpill"],
    [/\bwish\b/gi, "cope-wish"],
    [/\bdream\b/gi, "bluepilled fantasy"],
    [/\bdreaming\b/gi, "bluepill-fantasizing"],
    [/\bfantasy\b/gi, "bluepilled delusion"],
    [/\billusion\b/gi, "frauded perception"],
    [/\bdenying\b/gi, "turbo-coping"],
    [/\baccepting\b/gi, "swallowing the pill"],
    [/\baccepted\b/gi, "swallowed the pill"],
    [/\bignoring\b/gi, "perception-thresholding"],
    [/\bignored\b/gi, "sub-perception-thresholded"],

    // ── Value / status ────────────────────────────────────────────────────
    [/\bvalue\b/gi, "SMV"],
    [/\bworth\b/gi, "sexual market value"],
    [/\bstatus\b/gi, "social proof"],
    [/\breputation\b/gi, "statusmaxx level"],
    [/\bfamous\b/gi, "high-status"],
    [/\bpopular\b/gi, "statusmaxxed"],
    [/\bunpopular\b/gi, "zero social proof"],
    [/\brich\b/gi, "wealthmaxxed"],
    [/\bwealthy\b/gi, "betabux-loaded"],
    [/\bmoney\b/gi, "betabux"],
    [/\bwealth\b/gi, "betabux reserves"],
    [/\bsalary\b/gi, "monthly betabux"],
    [/\bincome\b/gi, "betabux flow"],
    [/\bpoor\b/gi, "poorcel"],
    [/\bbroke\b/gi, "zero-betabux"],
    [/\bconfidence\b/gi, "stabilized aura"],
    [/\bcharisma\b/gi, "dark triad energy"],
    [/\bcharm\b/gi, "NT-maxxed rizz"],
    [/\bcharming\b/gi, "NT-pilled"],
    [/\bpersonable\b/gi, "NT-maxxed"],
    [/\bsocial\b/gi, "NT"],
    [/\bsocially\b/gi, "in an NT-pilled way"],
    [/\bconfident\b/gi, "aura-stabilized"],
    [/\binsecure\b/gi, "low-inhib-deficient"],
    [/\binsecurity\b/gi, "aura deficit"],
    [/\bpower\b/gi, "mog potential"],
    [/\bpowerful\b/gi, "peak mog potential"],
    [/\binfluence\b/gi, "social proof leverage"],
    [/\binfluential\b/gi, "statusmaxxed"],
    [/\brespect\b/gi, "mog acknowledgment"],
    [/\brespected\b/gi, "mog-acknowledged"],
    [/\bsuccessful\b/gi, "ascended"],
    [/\bsuccess\b/gi, "ascension"],

    // ── Emotions / states ─────────────────────────────────────────────────
    [/\bhappy\b/gi, "ascension-pilled"],
    [/\bhappiness\b/gi, "ascension state"],
    [/\bsad\b/gi, "blackpilled"],
    [/\bsadness\b/gi, "blackpill absorption"],
    [/\bdepressed\b/gi, "LDAR-adjacent"],
    [/\bdepression\b/gi, "chronic LDAR state"],
    [/\bangry\b/gi, "cortisol-spiked"],
    [/\banger\b/gi, "cortisol spike"],
    [/\bfurious\b/gi, "cortisol-NUKED"],
    [/\bstressed\b/gi, "cortisol-nuked"],
    [/\bstress\b/gi, "cortisol elevation"],
    [/\banxious\b/gi, "high-inhib-locked"],
    [/\banxiety\b/gi, "chronic high-inhib state"],
    [/\brelaxed\b/gi, "low-cortisol"],
    [/\bcalm\b/gi, "cortisol-stabilized"],
    [/\bnervous\b/gi, "high-inhibition"],
    [/\bbrave\b/gi, "low-inhibition"],
    [/\bbold\b/gi, "low-inhib"],
    [/\bscared\b/gi, "high-inhib-locked"],
    [/\bfear\b/gi, "high-inhib response"],
    [/\btired\b/gi, "sleep-deprived-coping"],
    [/\bexhausted\b/gi, "recovery-protocol-deficient"],
    [/\benergetic\b/gi, "adrenal-maxxed"],
    [/\benergy\b/gi, "aura output"],
    [/\bmotivated\b/gi, "locked-in"],
    [/\bmotivation\b/gi, "grindset fuel"],
    [/\bunmotivated\b/gi, "LDAR-adjacent"],
    [/\bfocused\b/gi, "DEEPLOCKED IN"],
    [/\bfocus\b/gi, "deeplock state"],
    [/\bbored\b/gi, "understimulated"],
    [/\bjealous\b/gi, "mega-coping"],
    [/\bjealousy\b/gi, "cope-fueled envy"],
    [/\benvious\b/gi, "seething"],
    [/\benvy\b/gi, "seethe"],
    [/\bproud\b/gi, "aura-elevated"],
    [/\bpride\b/gi, "aura elevation"],
    [/\bshame\b/gi, "PSL shame spiral"],
    [/\bashamed\b/gi, "PSL-shamed"],
    [/\bembarrassed\b/gi, "publicly mogged"],
    [/\bsurprised\b/gi, "mog-shocked"],
    [/\bshocked\b/gi, "blackpill-struck"],
    [/\bdisgusted\b/gi, "subhuman-exposure reaction"],
    [/\bexcited\b/gi, "ascension-anticipating"],
    [/\blonely\b/gi, "isolated-celling"],
    [/\bloneliness\b/gi, "chronic isolation-cel state"],
    [/\bcrazy\b/gi, "mentalcel-tier"],
    [/\binsane\b/gi, "schizo-tier"],

    // ── Relationships / dating ────────────────────────────────────────────
    [/\bgirlfriend\b/gi, "LTR stacy"],
    [/\bboyfriend\b/gi, "chad BF"],
    [/\brelationship\b/gi, "LTR"],
    [/\brelationships\b/gi, "LTRs"],
    [/\bdating\b/gi, "plate-spinning"],
    [/\bdate\b/gi, "IOI opportunity"],
    [/\bdates\b/gi, "IOI opportunities"],
    [/\bflirt\b/gi, "run game on"],
    [/\bflirting\b/gi, "running game"],
    [/\bflirted\b/gi, "ran game on"],
    [/\bmarried\b/gi, "pair-bonded"],
    [/\bmarriage\b/gi, "pair-bonding contract"],
    [/\bwedding\b/gi, "pair-bonding ceremony"],
    [/\bdivorce\b/gi, "betabux extraction event"],
    [/\bdivorced\b/gi, "betabux-extracted"],
    [/\bbreakup\b/gi, "branch-swing event"],
    [/\bsingle\b/gi, "unmatched on the market"],
    [/\blove\b/gi, "pair-bonding instinct"],
    [/\bloving\b/gi, "pair-bond-driven"],
    [/\bloved\b/gi, "pair-bonded with"],
    [/\bsex\b/gi, "ascension"],
    [/\bkiss\b/gi, "IOI confirmation"],
    [/\bkissing\b/gi, "IOI confirming"],
    [/\bhug\b/gi, "frame contact"],
    [/\bhugging\b/gi, "frame-contacting"],
    [/\brejected\b/gi, "IOI-denied"],
    [/\brejection\b/gi, "IOI denial"],
    [/\battention\b/gi, "IOIs"],
    [/\bcompliment\b/gi, "verbal IOI"],
    [/\bcompliments\b/gi, "verbal IOIs"],
    [/\bstaring\b/gi, "DEEPLOCKING on"],
    [/\bstared\b/gi, "DEEPLOCKED on"],
    [/\bstare\b/gi, "deeplock"],
    [/\bcheating\b/gi, "branch-swinging"],
    [/\bcheated\b/gi, "branch-swung"],
    [/\bproposed\b/gi, "initiated pair-bonding protocol"],
    [/\bswiping\b/gi, "SMV-sorting"],
    [/\bmatch\b/gi, "SMV-verified pairing"],
    [/\bmatches\b/gi, "SMV-verified pairings"],
    [/\btinder\b/gi, "the SMV sorting algorithm"],
    [/\bcheat\b/gi, "hypergamy-execute"],

    // ── Quality / degree ──────────────────────────────────────────────────
    [/\bvery\b/gi, "brutally"],
    [/\bextremely\b/gi, "PEAK"],
    [/\bincredibly\b/gi, "catastrophically"],
    [/\breally\b/gi, "genuinely"],
    [/\btruly\b/gi, "unironically"],
    [/\babsolutely\b/gi, "irreversibly"],
    [/\bcompletely\b/gi, "maxed-out"],
    [/\btotally\b/gi, "categorically"],
    [/\bslightly\b/gi, "sub-clinically"],
    [/\bsomewhat\b/gi, "quasi-"],
    [/\bseriously\b/gi, "unironically"],
    [/\bliterally\b/gi, "clinically"],
    [/\bobviously\b/gi, "per the blackpill"],
    [/\bclearly\b/gi, "PSL-evidently"],
    [/\bdefinitely\b/gi, "without frauding"],
    [/\bprobably\b/gi, "per preliminary PSL audit"],

    // ── Good / bad / size ─────────────────────────────────────────────────
    [/\bgood\b/gi, "high-tier"],
    [/\bgreat\b/gi, "elite-tier"],
    [/\bexcellent\b/gi, "mogger-tier"],
    [/\bamazing\b/gi, "GOAT-tier"],
    [/\bfantastic\b/gi, "gigachad-tier"],
    [/\bwonderful\b/gi, "ascension-tier"],
    [/\bincredible\b/gi, "reality-mogging"],
    [/\bperfect\b/gi, "PSL 9"],
    [/\bimpressive\b/gi, "mog-worthy"],
    [/\boutstanding\b/gi, "top-percentile PSL"],
    [/\bbad\b/gi, "sub-5"],
    [/\bterrible\b/gi, "sub-3"],
    [/\bawful\b/gi, "truecel-tier"],
    [/\bhorrible\b/gi, "subhuman-tier"],
    [/\bdisgusting\b/gi, "negative PSL"],
    [/\bpathetic\b/gi, "LDAR-inducing"],
    [/\bhuge\b/gi, "frame-filling"],
    [/\bbig\b/gi, "frame-mog-tier"],
    [/\blarge\b/gi, "frame-dominant"],
    [/\bsmall\b/gi, "wristcel-tier"],
    [/\btiny\b/gi, "micro-framed"],
    [/\bmassive\b/gi, "absolute unit-tier"],
    [/\benormous\b/gi, "gigaframe"],
    [/\bfast\b/gi, "speedrun-tier"],
    [/\bslow\b/gi, "lag-tier"],
    [/\bnew\b/gi, "fresh"],
    [/\bold\b/gi, "post-wall"],
    [/\byoung\b/gi, "pre-wall"],
    [/\bnice\b/gi, "halo-having"],
    [/\bworse\b/gi, "more failo-ridden"],
    [/\bbest\b/gi, "peak PSL"],
    [/\bworst\b/gi, "lowest-tier PSL"],

    // ── Actions / perception ──────────────────────────────────────────────
    [/\bsaw\b/gi, "CLOCKED"],
    [/\bseen\b/gi, "CLOCKED"],
    [/\bsee\b/gi, "clock"],
    [/\bseeing\b/gi, "clocking"],
    [/\bnoticed\b/gi, "CLOCKED"],
    [/\bnotice\b/gi, "clock"],
    [/\brecognize\b/gi, "PSL-identify"],
    [/\brecognized\b/gi, "PSL-identified"],
    [/\bwalking\b/gi, "frame-displaying"],
    [/\bwalked\b/gi, "frame-displayed"],
    [/\bwalk\b/gi, "frame-display"],
    [/\bstanding\b/gi, "holding frame"],
    [/\bstand\b/gi, "hold frame"],
    [/\bsitting\b/gi, "frame-compressing"],
    [/\bsit\b/gi, "frame-compress"],
    [/\benter\b/gi, "mog-enter"],
    [/\bentered\b/gi, "mog-entered"],
    [/\bentering\b/gi, "mog-entering"],
    [/\bleave\b/gi, "de-mog"],
    [/\bleft\b/gi, "de-mogged"],
    [/\btrying\b/gi, "attempting to ascend"],
    [/\btry\b/gi, "attempt ascension"],
    [/\btried\b/gi, "attempted ascension"],
    [/\bfailed\b/gi, "descended the PSL chart"],
    [/\bfail\b/gi, "descend the PSL chart"],
    [/\bsucceed\b/gi, "ascend"],
    [/\bsucceeded\b/gi, "ascended"],
    [/\bstruggle\b/gi, "cope-battle"],
    [/\bstruggling\b/gi, "cope-battling"],
    [/\blaugh\b/gi, "mog-laugh"],
    [/\blaughing\b/gi, "mog-laughing"],
    [/\blaughed\b/gi, "mog-laughed"],
    [/\bcry\b/gi, "blackpill-absorb"],
    [/\bcrying\b/gi, "blackpill-absorbing"],
    [/\bcried\b/gi, "blackpill-absorbed"],
    [/\bthink\b/gi, "PSL-assess"],
    [/\bthinking\b/gi, "PSL-assessing"],
    [/\bwant\b/gi, "aspire to ascend toward"],
    [/\bwanted\b/gi, "aspired to ascend toward"],
    [/\bneed\b/gi, "require for ascension"],

    // ── Misc concepts ─────────────────────────────────────────────────────
    [/\bproblem\b/gi, "fatal failo"],
    [/\bproblems\b/gi, "fatal failos"],
    [/\bmistake\b/gi, "irreversible PSL bleed"],
    [/\bmistakes\b/gi, "irreversible PSL bleeds"],
    [/\bsolution\b/gi, "surgical intervention"],
    [/\bsolutions\b/gi, "intervention protocols"],
    [/\bresults\b/gi, "ascension outcomes"],
    [/\bresult\b/gi, "ascension outcome"],
    [/\bsecret\b/gi, "blackpilled truth"],
    [/\bsecrets\b/gi, "blackpilled truths"],
    [/\btruth\b/gi, "blackpill"],
    [/\bfact\b/gi, "blackpill data point"],
    [/\bfacts\b/gi, "blackpill data"],
    [/\bopinion\b/gi, "cope-take"],
    [/\bopinions\b/gi, "cope-takes"],
    [/\badvice\b/gi, "looksmaxxing protocol"],
    [/\btips\b/gi, "softmaxx protocols"],
    [/\btip\b/gi, "PSL tip"],
    [/\blife\b/gi, "genetic lottery outcome"],
    [/\blucky\b/gi, "genetically gifted"],
    [/\bunlucky\b/gi, "genetically cursed"],
    [/\bgenetics\b/gi, "genetic lottery"],
    [/\bgenetic\b/gi, "hereditary RNG"],
    [/\bDNA\b/gi, "genetic source code"],
    [/\bnatural\b/gi, "unfrauded"],
    [/\bnaturally\b/gi, "without frauding"],
    [/\brandom\b/gi, "RNG-determined"],
    [/\bchance\b/gi, "genetic lottery probability"],
    [/\bpotential\b/gi, "ceiling PSL"],
    [/\blimit\b/gi, "genetic ceiling"],
    [/\blimits\b/gi, "genetic ceilings"],

    // ── Time / routine ────────────────────────────────────────────────────
    [/\bmorning\b/gi, "AM cortisol window"],
    [/\bevening\b/gi, "PM cortisol window"],
    [/\bnight\b/gi, "melatonin production phase"],
    [/\btoday\b/gi, "current cortisol cycle"],
    [/\byesterday\b/gi, "previous cortisol cycle"],
    [/\btomorrow\b/gi, "next cortisol cycle"],
    [/\bweekend\b/gi, "recovery protocol window"],
    [/\byear\b/gi, "rotation around the UV source"],
    [/\byears\b/gi, "rotations around the UV source"],
    [/\bmonth\b/gi, "maxxing cycle"],
    [/\bmonths\b/gi, "maxxing cycles"],
    [/\bweek\b/gi, "micro-cycle"],
    [/\bweeks\b/gi, "micro-cycles"],
    [/\bage\b/gi, "wall proximity index"],
    [/\baging\b/gi, "wall-approaching"],
    [/\bbirthday\b/gi, "spawn anniversary"],

    // ── Places ────────────────────────────────────────────────────────────
    [/\bschool\b/gi, "social hierarchy arena"],
    [/\bcollege\b/gi, "peak SMV testing ground"],
    [/\buniversity\b/gi, "the SMV proving grounds"],
    [/\bjob\b/gi, "betabux source"],
    [/\bwork\b/gi, "betabux grind"],
    [/\bcareer\b/gi, "statusmaxx trajectory"],
    [/\boffice\b/gi, "betabux facility"],
    [/\bparty\b/gi, "IOI farming event"],
    [/\bparties\b/gi, "IOI farming events"],
    [/\bbar\b/gi, "nighttime mog-arena"],
    [/\bclub\b/gi, "dark-lighting fraudzone"],
    [/\bbeach\b/gi, "frame-exposure zone"],
    [/\bpool\b/gi, "frame-audit zone"],
    [/\bmall\b/gi, "softmaxx supply depot"],
    [/\bhospital\b/gi, "hardmaxx facility"],
    [/\bdoctor\b/gi, "hardmaxx consultant"],
    [/\bdentist\b/gi, "maxillary technician"],
    [/\bcity\b/gi, "geo-location"],
    [/\btown\b/gi, "low-tier geo-location"],
    [/\bcountry\b/gi, "geomaxx destination"],
    [/\bhome\b/gi, "base of operations"],
    [/\bhouse\b/gi, "statusmaxx shelter"],
    [/\bapartment\b/gi, "cope quarters"],
    [/\bbathroom\b/gi, "PSL audit chamber"],
    [/\bmirror\b/gi, "cope-reflector"],
    [/\bcamera\b/gi, "lens distortion device"],
    [/\brestaurant\b/gi, "macro intake venue"],

    // ── Food / health / substances ────────────────────────────────────────
    [/\bfood\b/gi, "macros"],
    [/\bbreakfast\b/gi, "AM macro intake"],
    [/\blunch\b/gi, "midday macro intake"],
    [/\bdinner\b/gi, "PM macro intake"],
    [/\bmeal\b/gi, "macro intake"],
    [/\bmeals\b/gi, "macro intakes"],
    [/\bprotein\b/gi, "anabolic fuel"],
    [/\bcarbs\b/gi, "glycogen fuel"],
    [/\bcalories\b/gi, "energy units"],
    [/\bsnack\b/gi, "micro macro intake"],
    [/\bcoffee\b/gi, "cortisol-spike fluid"],
    [/\btea\b/gi, "low-cortisol hydration"],
    [/\bwater\b/gi, "hydration fluid"],
    [/\balcohol\b/gi, "collagen-destroying poison"],
    [/\bbeer\b/gi, "bloatmaxx fluid"],
    [/\bwine\b/gi, "resveratrol cope-drink"],
    [/\bsmoking\b/gi, "accelerated wall-approach protocol"],
    [/\bcigarette\b/gi, "collagen destruction stick"],
    [/\bcigarettes\b/gi, "collagen destruction sticks"],
    [/\bdrug\b/gi, "neurotransmitter fraud"],
    [/\bdrugs\b/gi, "neurotransmitter frauds"],
    [/\bsleep\b/gi, "recovery protocol"],
    [/\bsleeping\b/gi, "executing recovery protocol"],
    [/\bnap\b/gi, "micro-recovery protocol"],
    [/\bvitamin\b/gi, "micronutrient"],
    [/\bvitamins\b/gi, "micronutrients"],
    [/\bsupplement\b/gi, "maxxing catalyst"],
    [/\bsupplements\b/gi, "maxxing catalysts"],
    [/\bcreatine\b/gi, "ATP-maxxing compound"],
    [/\bsteroids\b/gi, "roidmaxx compounds"],
    [/\btestosterone\b/gi, "T-level"],
    [/\bestrogen\b/gi, "anti-dimorphism hormone"],
    [/\bcortisol\b/gi, "cortisol"],
    [/\binsulin\b/gi, "glycemic response hormone"],
    [/\bcollagen\b/gi, "dermal structural protein"],

    // ── Weather / environment ─────────────────────────────────────────────
    [/\bweather\b/gi, "UV index conditions"],
    [/\brain\b/gi, "zero-UV window"],
    [/\bsunny\b/gi, "high UV exposure risk"],
    [/\bsun\b/gi, "UV radiation source"],
    [/\bsunlight\b/gi, "UV exposure"],
    [/\bcloud\b/gi, "natural UV filter"],
    [/\bclouds\b/gi, "natural UV filters"],
    [/\bhot\b/gi, "high UV index"],
    [/\bcold\b/gi, "vasoconstriction weather"],
    [/\bwinter\b/gi, "low-UV season"],
    [/\bsummer\b/gi, "peak UV damage season"],

    // ── Photography / media ───────────────────────────────────────────────
    [/\bphotos\b/gi, "PSL audits"],
    [/\bphoto\b/gi, "PSL audit"],
    [/\bpictures\b/gi, "fraudcheck material"],
    [/\bpicture\b/gi, "fraudcheck material"],
    [/\bselfie\b/gi, "self-PSL-audit"],
    [/\bselfies\b/gi, "self-PSL-audits"],
    [/\bvideo\b/gi, "motion PSL audit"],
    [/\bvideos\b/gi, "motion PSL audits"],
    [/\bfilter\b/gi, "digital fraud"],
    [/\bfilters\b/gi, "digital fraud stack"],
    [/\bphotoshop\b/gi, "pixel-level frauding"],
    [/\bedited\b/gi, "frauded"],
    [/\bangle\b/gi, "fraud angle"],
    [/\blighting\b/gi, "fraud lighting"],
    [/\bInstagram\b/gi, "the fraud platform"],
    [/\bTikTok\b/gi, "the looksmaxxing broadcast network"],
    [/\bsocial media\b/gi, "the SMV broadcasting platform"],
    [/\bprofile\b/gi, "digital phenotype display"],

    // ── Vehicles / possessions ────────────────────────────────────────────
    [/\bcar\b/gi, "statusmaxx vehicle"],
    [/\bcars\b/gi, "statusmaxx vehicles"],
    [/\bphone\b/gi, "fraudcheck device"],
    [/\blaptop\b/gi, "LDAR machine"],
    [/\bcomputer\b/gi, "LDAR station"],

    // ── Personality (as lookism sees it) ──────────────────────────────────
    [/\bpersonality\b/gi, "cope-tier trait"],
    [/\bkind\b/gi, "beta-trait"],
    [/\bgenerous\b/gi, "betabux-distributing"],
    [/\brude\b/gi, "dark triad"],
    [/\baggressive\b/gi, "low-inhib"],
    [/\bpassive\b/gi, "high-inhib"],
    [/\bintroverted\b/gi, "high-inhib"],
    [/\bextroverted\b/gi, "low-inhib NT-maxxed"],
    [/\bshy\b/gi, "high-inhib"],
    [/\boutgoing\b/gi, "low-inhib NT-maxxed"],
    [/\blazy\b/gi, "LDAR-pilled"],
    [/\bambitious\b/gi, "grindset-locked"],
    [/\bsmart\b/gi, "IQ-maxxed"],
    [/\bintelligent\b/gi, "high-IQ-specimen"],
    [/\bstupid\b/gi, "low-IQ-cel"],
    [/\bfunny\b/gi, "JesterMaxxed"],
    [/\bhumorous\b/gi, "JesterMaxxing"],
    [/\bserious\b/gi, "stoicmaxxed"],
    [/\bcreepy\b/gi, "uncanny valley PSL"],
    [/\bcreep\b/gi, "sub-5 with low inhib"],
    [/\bweird\b/gi, "mentalcel-coded"],
    [/\bnice guy\b/gi, "beta orbiter"],
  ],

  // =========================================================================
  //  LEVEL 2 — HARDMAXXED
  // =========================================================================
  2: [
    // ── Sentence-level rewrites ───────────────────────────────────────────
    [/\bI think\b/gi, "after running the PSL analytics I conclude"],
    [/\bI believe\b/gi, "the blackpill data confirms"],
    [/\bI feel\b/gi, "my cortisol levels indicate"],
    [/\bI know\b/gi, "the mog-data is clear that"],
    [/\bI hope\b/gi, "in a supreme act of cope I hope"],
    [/\bI want\b/gi, "my SMV demands"],
    [/\bI need\b/gi, "ascension requires"],
    [/\bIn my opinion\b/gi, "Per my cranial assessment"],
    [/\bTo be honest\b/gi, "After careful mog-analysis"],
    [/\bfor example\b/gi, "as demonstrated in this mog-comparison"],
    [/\bhowever\b/gi, "BUT HERE'S THE BRUTAL MOGPILL"],
    [/\btherefore\b/gi, "and thus the mog hierarchy dictates"],
    [/\bfurthermore\b/gi, "stacking this on the PSL chart"],
    [/\bnevertheless\b/gi, "despite the brutal mogging"],
    [/\baccording to\b/gi, "the PSL database confirms"],
    [/\bmeanwhile\b/gi, "on the other side of the mog-spectrum"],
    [/\bin conclusion\b/gi, "FINAL PSL VERDICT"],
    [/\bfinally\b/gi, "after exhaustive mog-analysis"],
    [/\bI am\b/gi, "this specimen is"],
    [/\bI'm\b/gi, "this specimen's"],
    [/\bI was\b/gi, "this specimen was"],
    [/\bI have\b/gi, "this specimen has"],
    [/\bI've\b/gi, "this specimen has"],
    [/\bmy\b/gi, "this specimen's"],

    // ── -cel compounds ────────────────────────────────────────────────────
    [/\bvirgin\b/gi, "truecel"],
    [/\bnerd\b/gi, "STEMcel"],
    [/\bnerds\b/gi, "STEMcels"],
    [/\bworker\b/gi, "wagecel"],
    [/\bworkers\b/gi, "wagecels"],
    [/\bloser\b/gi, "subhuman-tier cel"],
    [/\blosers\b/gi, "sub-5 cels"],
    [/\bloner\b/gi, "mentalcel"],
    [/\bloners\b/gi, "mentalcels"],
    [/\bgamer\b/gi, "LDARcel"],
    [/\bgamers\b/gi, "LDARcels"],
    [/\bvolunteer\b/gi, "volcel"],
    [/\bcoward\b/gi, "high-inhib-cel"],
    [/\bfollower\b/gi, "beta orbiter"],
    [/\bfollowers\b/gi, "beta orbiters"],
    [/\bfan\b/gi, "orbiter"],
    [/\bfans\b/gi, "orbiters"],
    [/\bcustomer\b/gi, "betabux dispensary client"],
    [/\bcustomers\b/gi, "betabux dispensary clients"],

    // ── -pilled compounds ─────────────────────────────────────────────────
    [/\baware\b/gi, "blackpilled"],
    [/\bunaware\b/gi, "bluepilled"],
    [/\boptimistic\b/gi, "whitepilled"],
    [/\bpessimistic\b/gi, "blackpill-overdosed"],
    [/\brealistic\b/gi, "PSL-calibrated"],
    [/\bnaive\b/gi, "bluepill-maxed"],
    [/\binformed\b/gi, "lore-pilled"],
    [/\beducated\b/gi, "knowledge-pilled"],
    [/\bcurious\b/gi, "pill-seeking"],
    [/\bskeptical\b/gi, "redpill-adjacent"],
    [/\bwoke\b/gi, "blackpilled"],
    [/\benlightened\b/gi, "mega-pilled"],
    [/\bconfused\b/gi, "between-pills"],
    [/\bconvinced\b/gi, "fully-pilled"],
    [/\breligious\b/gi, "faith-pilled"],
    [/\batheist\b/gi, "nihilism-pilled"],

    // ── -fraud compounds ──────────────────────────────────────────────────
    [/\bcontacts\b/gi, "iris-frauding lenses"],
    [/\bwigs?\b/gi, "Norwood-fraud system"],
    [/\blifts\b/gi, "height-frauding devices"],
    [/\bheels\b/gi, "height-fraud platforms"],
    [/\bpadding\b/gi, "frame-frauding material"],
    [/\bhair extensions\b/gi, "follicular fraud"],
    [/\bbraces\b/gi, "maxillary realignment fraud"],
    [/\bfiller\b/gi, "injectable fraud"],
    [/\bfillers\b/gi, "injectable fraud compounds"],
    [/\bbotox\b/gi, "wrinkle-fraud injection"],
    [/\bimplant\b/gi, "surgical fraud device"],
    [/\bimplants\b/gi, "surgical fraud devices"],

    // ── -maxxing compounds ────────────────────────────────────────────────
    [/\bstudying\b/gi, "IQmaxxing"],
    [/\blearning\b/gi, "knowledgemaxxing"],
    [/\breading\b/gi, "loremaxxing"],
    [/\bcooking\b/gi, "macromaxxing"],
    [/\bcleaning\b/gi, "hygienemaxxing"],
    [/\btraveling\b/gi, "geomaxxing"],
    [/\btravelling\b/gi, "geomaxxing"],
    [/\btravel\b/gi, "geomaxx"],
    [/\bmoving\b/gi, "geolocation-maxxing"],
    [/\bsinging\b/gi, "voicemaxxing"],
    [/\bdriving\b/gi, "statusmaxx-commuting"],
    [/\bshopping\b/gi, "softmaxx-acquiring"],
    [/\bdancing\b/gi, "rhythmmaxxing"],
    [/\bwriting\b/gi, "articulationmaxxing"],
    [/\bpainting\b/gi, "creativemaxxing"],
    [/\bworking\b/gi, "betabux-grinding"],
    [/\beating\b/gi, "macro-intaking"],

    // ── Deep PSL anatomy / procedures ─────────────────────────────────────
    [/\bsymmetry\b/gi, "facial harmony coefficient"],
    [/\bsymmetrical\b/gi, "harmonically balanced"],
    [/\basymmetrical\b/gi, "harmony-deficient"],
    [/\bproportion\b/gi, "golden ratio alignment"],
    [/\bproportional\b/gi, "golden-ratio-compliant"],
    [/\bfeatures\b/gi, "facial thirds distribution"],
    [/\bfeature\b/gi, "facial third element"],
    [/\bmasculine\b/gi, "dimorphism-maxxed"],
    [/\bfeminine\b/gi, "neotenous-featured"],
    [/\bandrogynous\b/gi, "dimorphism-neutral"],
    [/\byouthful\b/gi, "collagen-rich"],
    [/\bmature\b/gi, "collagen-depleted"],
    [/\bbig forehead\b/gi, "excessive frontal bone"],
    [/\bwide face\b/gi, "high fWHR"],
    [/\bnarrow face\b/gi, "low fWHR"],
    [/\blong face\b/gi, "horse-face-tier fWHR"],
    [/\bround face\b/gi, "buccal-fat-padded"],
    [/\bsquare jaw\b/gi, "gonial angle sub-120"],
    [/\bweak chin\b/gi, "recessed mental protuberance"],
    [/\bstrong jaw\b/gi, "elite gonial angle"],
    [/\bcrooked nose\b/gi, "deviated nasal septum"],
    [/\bbig nose\b/gi, "over-projected nasal bridge"],
    [/\bsmall nose\b/gi, "neotenous nasal profile"],
    [/\bthin lips\b/gi, "vermilion-deficient"],
    [/\bfull lips\b/gi, "vermilion-maxxed"],
    [/\bdouble eyelid\b/gi, "epicanthic-fold-free"],
    [/\bmonolid\b/gi, "epicanthic-fold-present"],
    [/\bhollowed cheeks\b/gi, "buccal-fat-reduced"],
    [/\bchubby cheeks\b/gi, "buccal-fat-maxxed"],
    [/\bnose job\b/gi, "rhinoplasty"],
    [/\bjaw surgery\b/gi, "orthognathic intervention"],
    [/\bchin implant\b/gi, "genioplasty"],

    // ── Rating system deep lore ───────────────────────────────────────────
    [/\b1 out of 10\b/gi, "PSL 1 (truecel)"],
    [/\b2 out of 10\b/gi, "PSL 2 (subhuman)"],
    [/\b3 out of 10\b/gi, "PSL 3 (subhuman)"],
    [/\b4 out of 10\b/gi, "PSL 4 (LTN)"],
    [/\b5 out of 10\b/gi, "PSL 5 (MTN)"],
    [/\b6 out of 10\b/gi, "PSL 6 (HTN)"],
    [/\b7 out of 10\b/gi, "PSL 7 (Chadlite)"],
    [/\b8 out of 10\b/gi, "PSL 8 (Chad)"],
    [/\b9 out of 10\b/gi, "PSL 9 (Gigachad)"],
    [/\b10 out of 10\b/gi, "PSL 10 (theoretical maximum)"],
    [/\b(\d)\/10\b/g, "PSL $1"],

    // ── Behavioral / social dynamics ──────────────────────────────────────
    [/\bbullying\b/gi, "social mogging"],
    [/\bbullied\b/gi, "socially mogged"],
    [/\bbully\b/gi, "social mogger"],
    [/\bfighting\b/gi, "frame-checking"],
    [/\bfight\b/gi, "frame-check encounter"],
    [/\barguing\b/gi, "verbal mog-battle"],
    [/\bargument\b/gi, "verbal mog-off"],
    [/\binsult\b/gi, "PSL-attack"],
    [/\binsulted\b/gi, "PSL-attacked"],
    [/\bjudging\b/gi, "PSL-auditing"],
    [/\bjudge\b/gi, "PSL-audit"],
    [/\bjudged\b/gi, "PSL-audited"],
    [/\bgossip\b/gi, "PSL intel"],
    [/\brumor\b/gi, "unverified PSL intel"],
    [/\bopinion\b/gi, "cope-take"],
    [/\bcriticism\b/gi, "constructive mogpill"],
    [/\bcritique\b/gi, "PSL assessment"],
    [/\brate\b/gi, "PSL-rate"],
    [/\brated\b/gi, "PSL-rated"],
    [/\brating\b/gi, "PSL rating"],
    [/\bcomparison\b/gi, "mog-analysis"],
    [/\bcomparing\b/gi, "mog-analyzing"],

    // ── Society / world in lookism terms ──────────────────────────────────
    [/\bsociety\b/gi, "the lookism hierarchy"],
    [/\bculture\b/gi, "the PSL meta"],
    [/\beconomy\b/gi, "the betabux ecosystem"],
    [/\bpolitics\b/gi, "statusmaxx theater"],
    [/\bgovernment\b/gi, "the NT bureaucracy"],
    [/\blaw\b/gi, "normie regulation"],
    [/\blaws\b/gi, "normie regulations"],
    [/\brules\b/gi, "social hierarchy protocols"],
    [/\brule\b/gi, "social hierarchy protocol"],
    [/\btradition\b/gi, "ancestral cope"],
    [/\bnature\b/gi, "genetic expression environment"],
    [/\bevolution\b/gi, "sexual selection pressure"],
    [/\bscience\b/gi, "blackpill research"],
    [/\bresearch\b/gi, "PSL data collection"],
    [/\bstudy\b/gi, "blackpill study"],
    [/\bdata\b/gi, "PSL metrics"],
    [/\bstatistics\b/gi, "blackpill statistics"],
    [/\btheory\b/gi, "pill-theory"],
    [/\bconcept\b/gi, "PSL framework element"],
  ],

  // =========================================================================
  //  LEVEL 3 — GIGAMOGGED (full unhinged mode)
  // =========================================================================
  3: [
    // ── Question words → unhinged but readable ──────────────────────────
    [/\bwhat\b/gi, "WHAT in the PSL"],
    [/\bwhy\b/gi, "WHY on this cursed timeline"],
    [/\bhow\b/gi, "HOW in the mog-hierarchy"],
    [/\bwho\b/gi, "WHICH specimen"],
    [/\bwhere\b/gi, "WHERE in the mog-arena"],

    // ── Connectors → chaotic but still sentence-readable ─────────────────
    [/\bbecause\b/gi, "due to IRREVERSIBLE genetic factors"],
    [/\bbut\b/gi, "BUT HOLD ON—"],
    [/\balso\b/gi, "FURTHERMORE"],
    [/\bactually\b/gi, "UPON DEEPER PSL INSPECTION"],
    [/\bjust\b/gi, "LITERALLY"],
    [/\bonly\b/gi, "BY A MILLIMETER"],
    [/\bmaybe\b/gi, "pending mog-analysis"],
    [/\bprobably\b/gi, "almost CERTAINLY per the blackpill"],
    [/\byes\b/gi, "CONFIRMED"],
    [/\bno\b/gi, "DENIED"],
    [/\bok\b/gi, "acknowledged"],
    [/\bthanks\b/gi, "mog-acknowledged"],
    [/\bthank you\b/gi, "mog-acknowledged respectfully"],
    [/\bsorry\b/gi, "COPE—my fault"],

    // ── Pronouns → light touch, keep it readable ─────────────────────────
    [/\byou\b/gi, "u"],
    [/\byour\b/gi, "ur"],
    [/\byou're\b/gi, "u r"],
    [/\bthey\b/gi, "they"],
    [/\bwe\b/gi, "the collective"],
    [/\bhe\b/gi, "the specimen"],
    [/\bhis\b/gi, "the specimen's"],
    [/\bshe\b/gi, "she"],
    [/\bher\b/gi, "her"],
  ],
};

// Sentence endings for level 3 — authentic lookism forum energy
const sentenceEndings = [
  " — BRUTAL mogpill",
  " it's OVER",
  " COPE or ROPE",
  " and that's the blackpill",
  " — irreversible PSL bleed BY A MILLIMETER",
  " absolute FRAME CHECK",
  " CLOCKED PEAK COPE",
  " the mog was CATASTROPHIC",
  " mogger-tier ascension outcome",
  " — cortisol NUKED",
  " DEEPLOCKED IN nuked cortisol stabilized AURA",
  " the gonial angle doesn't lie",
  " the mandible has spoken",
  " brutal heightmog detected",
  " SMV in FREEFALL",
  " genetic lottery = RIGGED",
  " PSL chart = DECIMATED",
  " just run [trait]maxxing bro",
  " — this is what PEAK ascension looks like",
  " zygomatic arches = CONFIRMED",
  " canthal tilt = POSITIVE",
  " Norwood status = STABLE (for now)",
  " the mewing is PAYING OFF",
  " bonesmashing WAS the answer all along",
  " frame = HELD",
  " aura = STABILIZED",
  " SKULLMOGGED beyond recovery",
  " the blackpill strikes again",
  " — another specimen BRUTALLY mogged",
  " not even hardmaxxing can save this",
];

// ---------------------------------------------------------------------------
// TEXT REPLACEMENT ENGINE
// ---------------------------------------------------------------------------

function getReplacements(level) {
  let replacements = [];
  for (let i = 1; i <= level; i++) {
    replacements = replacements.concat(slangLevels[i] || []);
  }
  return replacements;
}

function convertText(text, level) {
  const replacements = getReplacements(level);
  let result = text;

  for (const [pattern, replacement] of replacements) {
    result = result.replace(pattern, (match) => {
      // At level 3 we keep the chaotic casing from the dictionary
      if (level >= 3) return replacement;
      // Preserve capitalization of first letter for levels 1-2
      if (
        match[0] === match[0].toUpperCase() &&
        match[0] !== match[0].toLowerCase()
      ) {
        return replacement.charAt(0).toUpperCase() + replacement.slice(1);
      }
      return replacement;
    });
  }

  // At level 2+, randomly CAPS-lock some words for emphasis
  if (level >= 2) {
    result = result.replace(/\b[a-z]{5,}\b/g, (word) => {
      return Math.random() < 0.05 ? word.toUpperCase() : word;
    });
  }

  // At level 3, append unhinged sentence endings
  if (level >= 3) {
    result = result.replace(/([.!?])(\s|$)/g, (match, punct, space) => {
      if (Math.random() < 0.35) {
        const ending =
          sentenceEndings[Math.floor(Math.random() * sentenceEndings.length)];
        return ending + punct + space;
      }
      return match;
    });
  }

  return result;
}

// ---------------------------------------------------------------------------
// DOM TRAVERSAL — walk all text nodes, skip scripts/styles/inputs
// ---------------------------------------------------------------------------

const SKIP_TAGS = new Set([
  "SCRIPT",
  "STYLE",
  "NOSCRIPT",
  "TEXTAREA",
  "INPUT",
  "CODE",
  "PRE",
  "SVG",
]);

function getTextNodes(root) {
  const nodes = [];
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      if (SKIP_TAGS.has(node.parentElement?.tagName)) {
        return NodeFilter.FILTER_REJECT;
      }
      if (node.textContent.trim().length === 0) {
        return NodeFilter.FILTER_REJECT;
      }
      return NodeFilter.FILTER_ACCEPT;
    },
  });
  while (walker.nextNode()) {
    nodes.push(walker.currentNode);
  }
  return nodes;
}

function convertPage(level) {
  const textNodes = getTextNodes(document.body);
  for (const node of textNodes) {
    if (!originalTexts.has(node)) {
      originalTexts.set(node, node.textContent);
    }
    const original = originalTexts.get(node);
    node.textContent = convertText(original, level);
  }
}

function revertPage() {
  for (const [node, original] of originalTexts) {
    try {
      node.textContent = original;
    } catch (_) {
      // Node may have been removed from DOM
    }
  }
  originalTexts.clear();
}

// ---------------------------------------------------------------------------
// MESSAGE LISTENER
// ---------------------------------------------------------------------------

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.action === "convert") {
    convertPage(message.intensity || 2);
    sendResponse({ status: "converted" });
  } else if (message.action === "revert") {
    revertPage();
    sendResponse({ status: "reverted" });
  }
});

chrome.storage.local.get(["enabled", "intensity"], (data) => {
  if (data.enabled) {
    convertPage(data.intensity || 2);
  }
});
